[org-modern-indent]
src.git = "https://github.com/jdtsmith/org-modern-indent"
src.branch = "main"
fetch.github = "jdtsmith/org-modern-indent"

[ol-emacs-slack]
src.git = "https://github.com/ag91/ol-emacs-slack"
src.branch = "master"
fetch.github = "ag91/ol-emacs-slack"

[org-roam-review]
src.git = "https://github.com/chrisbarrett/nursery"
src.branch = "main"
fetch.github = "chrisbarrett/nursery"

[gcal]
src.git = "https://github.com/misohena/gcal"
src.branch = "master"
fetch.github = "misohena/gcal"

[typst-preview]
src.git = "https://github.com/havarddj/typst-preview.el"
src.branch = "main"
fetch.github = "havarddj/typst-preview.el"

[vivaldi-darwin]
src.archpkg = "vivaldi"
fetch.url = "https://downloads.vivaldi.com/stable/Vivaldi.$ver.universal.dmg"

[qutebrowser-darwin]
src.github = "qutebrowser/qutebrowser"
src.prefix = "v"
fetch.url = "https://github.com/qutebrowser/qutebrowser/releases/download/v$ver/qutebrowser-$ver-arm64.dmg"

[claude-code-ide]
src.git = "https://github.com/manzaltu/claude-code-ide.el"
src.branch = "main"
fetch.github = "manzaltu/claude-code-ide.el"

[aquaskk]
src.github_tag = "codefirst/aquaskk"
fetch.url ="https://github.com/codefirst/aquaskk/releases/download/$ver/AquaSKK-$ver.pkg"

[cskk]
src.git = "https://github.com/naokiri/cskk"
fetch.github = "naokiri/cskk"

[niri-taskbar]
src.github_tag = "LawnGnome/niri-taskbar"
fetch.github = "LawnGnome/niri-taskbar"

[nx-zotero]
src.git = "https://github.com/rolling-robot/nx-zotero"
src.branch = "master"
fetch.github = "rolling-robot/nx-zotero"

[bizin-gothic-nf]
src.github = "yuru7/bizin-gothic"
src.prefix = "v"
fetch.url = "https://github.com/yuru7/bizin-gothic/releases/download/v$ver/BizinGothicNF_v$ver.zip"

[nx-rbw]
src.git = "https://codeberg.org/ablatedsprocket/nx-rbw"
src.branch = "main"
fetch.url = "https://codeberg.org/ablatedsprocket/nx-rbw/archive/main.tar.gz"

[fcitx5-cskk]
src.git = "https://github.com/fcitx/fcitx5-cskk"
src.branch = "master"
fetch.github = "fcitx/fcitx5-cskk"

[lean4-mode]
src.git = "https://github.com/leanprover-community/lean4-mode"
src.branch = "master"
fetch.github = "leanprover-community/lean4-mode"

[hledger-lots]
src.pypi = "hledger_lots"
fetch.pypi = "hledger_lots"

[pyxirr]
src.pypi = "pyxirr"
fetch.pypi = "pyxirr"

[rich-click]
src.pypi = "rich_click"
fetch.pypi = "rich_click"
